package com.paintology.lite.trace.drawing.Activity.favourite

import com.paintology.lite.trace.drawing.R

class CountriesList {

    companion object{
        fun getCountryFlagResource(countryCode: String): Int {
            return when (countryCode) {
                "AF" -> R.drawable.af___afghanistan
                "AL" -> R.drawable.al___albania
                "DZ" -> R.drawable.dz___algeria
                "AD" -> R.drawable.ad___andorra
                "AO" -> R.drawable.ao___angola
                "AR" -> R.drawable.ar___argentina
                "AM" -> R.drawable.am___armenia
                "AU" -> R.drawable.au___australia
                "AT" -> R.drawable.at___austria
                "AZ" -> R.drawable.az___azerbaijan
                "BS" -> R.drawable.bs___bahamas
                "BH" -> R.drawable.bh___bahrain
                "BD" -> R.drawable.bd___bangladesh
                "BB" -> R.drawable.bb___barbados
                "BY" -> R.drawable.by___belarus
                "BE" -> R.drawable.be___belgium
                "BZ" -> R.drawable.bz___belize
                "BJ" -> R.drawable.bj___benin
                "BT" -> R.drawable.bt___bhutan
                "BO" -> R.drawable.bo___bolivia
                "BA" -> R.drawable.ba___bosnia_and_herzegovina
                "BW" -> R.drawable.bw___botswana
                "BR" -> R.drawable.br___brazil
                "BN" -> R.drawable.bn___brunei_darussalam
                "BG" -> R.drawable.bg___bulgaria
                "BF" -> R.drawable.bf___burkina_faso
                "BI" -> R.drawable.bi___burundi
                "KH" -> R.drawable.kh___cambodia
                "CM" -> R.drawable.cm___cameroon
                "CA" -> R.drawable.ca___canada
                "TD" -> R.drawable.td___chad
                "CL" -> R.drawable.cl___chile
                "CN" -> R.drawable.cn___china
                "CO" -> R.drawable.co___colombia
                "KM" -> R.drawable.km___comoros
                "CG" -> R.drawable.cg___republic_of_the_congo
                "HR" -> R.drawable.hr___croatia__hrvatska_
                "CU" -> R.drawable.cu___cuba
                "CY" -> R.drawable.cy___cyprus
                "CZ" -> R.drawable.cz___czech_republic
                "DK" -> R.drawable.dk___denmark
                "DJ" -> R.drawable.dj___djibouti
                "DM" -> R.drawable.dm___dominica
                "DO" -> R.drawable.do___dominican_republic
                "EC" -> R.drawable.ec___ecuador
                "EG" -> R.drawable.eg___egypt
                "ER" -> R.drawable.er___eritrea
                "EE" -> R.drawable.ee___estonia
                "ET" -> R.drawable.et___ethiopia
                "FJ" -> R.drawable.fj___fiji
                "FI" -> R.drawable.fi___finland
                "FR" -> R.drawable.flag_france
                "GA" -> R.drawable.ga___gabon
                "GM" -> R.drawable.gm___gambia
                "GE" -> R.drawable.ge___georgia
                "DE" -> R.drawable.de___germany
                "GH" -> R.drawable.gh___ghana
                "GR" -> R.drawable.gr___greece
                "GD" -> R.drawable.gd___grenada
                "GT" -> R.drawable.gt___guatemala
                "GN" -> R.drawable.gn___guinea
                "GY" -> R.drawable.gy___guyana
                "HT" -> R.drawable.ht___haiti
                "HN" -> R.drawable.hn___honduras
                "HU" -> R.drawable.hu___hungary
                "IS" -> R.drawable.is___iceland
                "IN" -> R.drawable.in___india
                "ID" -> R.drawable.id___indonesia
                "IR" -> R.drawable.ir___iran
                "IQ" -> R.drawable.iq___iraq
                "IE" -> R.drawable.ie___ireland
                "IL" -> R.drawable.il___isreal
                "IT" -> R.drawable.it___italy
                "JM" -> R.drawable.jm___jamaica
                "JP" -> R.drawable.jp___japan
                "JO" -> R.drawable.jo___jordan
                "KZ" -> R.drawable.kz___kazakhstan
                "KE" -> R.drawable.ke___kenia
                "KI" -> R.drawable.ki____kiribati
                "KP" -> R.drawable.kp___korea__north_
                "KR" -> R.drawable.kr___korea__south_
                "XK" -> R.drawable.flag_kosovo
                "KW" -> R.drawable.kw___kuwait
                "KG" -> R.drawable.kg___kyrgyzstan
                "LA" -> R.drawable.la___laos
                "LV" -> R.drawable.lv___latvia
                "LB" -> R.drawable.lb___lebanon
                "LS" -> R.drawable.ls___lesotho
                "LR" -> R.drawable.lr___liberia
                "LY" -> R.drawable.ly___libya
                "LI" -> R.drawable.li___liechtenstein
                "LT" -> R.drawable.lt___lithuania
                "LU" -> R.drawable.lu___luxembourg
                "MK" -> R.drawable.mk___north_macedonia
                "MG" -> R.drawable.mg___madagascar
                "MW" -> R.drawable.mw___malawi
                "MY" -> R.drawable.my___malaysia
                "MV" -> R.drawable.mv___maldives
                "ML" -> R.drawable.ml___mali
                "MT" -> R.drawable.mt___malta
                "MH" -> R.drawable.mh___marshall_islands
                "MR" -> R.drawable.mr___mauritania
                "MU" -> R.drawable.mu___mauritius
                "MX" -> R.drawable.mx___mexico
                "FM" -> R.drawable.fm___federated_states_of_micronesia
                "MD" -> R.drawable.md___moldova
                "MC" -> R.drawable.mc___monaco
                "MN" -> R.drawable.mn___mongolia
                "ME" -> R.drawable.me___montenegro
                "MA" -> R.drawable.ma___morocco
                "MZ" -> R.drawable.mz___mozambique
                "MM" -> R.drawable.mm___myanmar
                "NA" -> R.drawable.na___namibia
                "NR" -> R.drawable.nr___nauru
                "NP" -> R.drawable.np___nepal
                "NL" -> R.drawable.nl___netherlands
                "NZ" -> R.drawable.nz___new_zealand__aotearoa_
                "NI" -> R.drawable.ni___nicaragua
                "NE" -> R.drawable.ne___niger
                "NG" -> R.drawable.ng___nigeria
                "NO" -> R.drawable.no___norway
                "OM" -> R.drawable.om___oman
                "PK" -> R.drawable.pk___pakistan
                "PW" -> R.drawable.pw___palau
                "PS" -> R.drawable.ps___palestinian_territory
                "PA" -> R.drawable.pa___panama
                "PG" -> R.drawable.pg___papua_new_guinea
                "PY" -> R.drawable.py___paraguay
                "PE" -> R.drawable.pe___peru
                "PH" -> R.drawable.ph___philippines
                "PL" -> R.drawable.pl___poland
                "PT" -> R.drawable.pt___portugal
                "QA" -> R.drawable.qa___qatar
                "RO" -> R.drawable.ro___romania
                "RS" -> R.drawable.rs___serbia
                "SC" -> R.drawable.sc___seychelles
                "SL" -> R.drawable.sl___sierra_leone
                "SG" -> R.drawable.sg___singapore
                "SK" -> R.drawable.sk___slovakia
                "SI" -> R.drawable.si___slovenia
                "SB" -> R.drawable.sb___solomon_islands
                "SO" -> R.drawable.so___somalia
                "ZA" -> R.drawable.za___south_africa
                "SS" -> R.drawable.ss___south_sudan
                "ES" -> R.drawable.es___spain
                "LK" -> R.drawable.lk___sri_lanka
                "SD" -> R.drawable.sd___sudan
                "SR" -> R.drawable.sr___suriname
                "SE" -> R.drawable.se___sweden
                "CH" -> R.drawable.ch___switzerland
                "SY" -> R.drawable.sy___syria
                "TW" -> R.drawable.tw___taiwan
                "TJ" -> R.drawable.tj___tajikistan
                "TZ" -> R.drawable.tz___tanzania
                "TH" -> R.drawable.th___thailand
                "TG" -> R.drawable.tg___togo
                "TO" -> R.drawable.to___tonga
                "TT" -> R.drawable.tt___trinidad_and_tobago
                "TN" -> R.drawable.tn___tunisia
                "TR" -> R.drawable.tr___turkey
                "TM" -> R.drawable.tm___turkmenistan
                "TV" -> R.drawable.tv___tuvalu
                "AE" -> R.drawable.img_uae
                "UG" -> R.drawable.ug___uganda
                "UA" -> R.drawable.ua___ukraine
                "GB" -> R.drawable.gb_ukm___united_kingdom
                "US" -> R.drawable.us___united_states
                "UY" -> R.drawable.uy___uruguay
                "UZ" -> R.drawable.uz___uzbekistan
                "VU" -> R.drawable.vu___vanuatu
                "VA" -> R.drawable.va___vatican_city_state
                "VE" -> R.drawable.ve___venezuela
                "VN" -> R.drawable.vn___vietnam
                "YE" -> R.drawable.ye___yemen
                "ZM" -> R.drawable.zm___zambia
                "ZW" -> R.drawable.zw___zimbabwe
                else -> R.drawable.img_world
            }
        }
    }

}